In [1]:
import torch
import torchvision
import numpy as np
from torch.utils.data import DataLoader
from torch import optim
import torch.nn as nn
from torch.nn import functional as F
from torchvision import transforms

In [44]:
#Loading Dataset
train_set = torchvision.datasets.MNIST("./data", train=True, download=True,
                                   transform=transforms.Compose(
                [transforms.ToTensor()]))
test_set = torchvision.datasets.MNIST("./data", train=False, download=True)

train_set_loader = DataLoader(train_set, batch_size= 128, num_workers=2)
test_set_loader = DataLoader(test_set, batch_size=128, num_workers=2)

# for indx, x, y in train_set_loader:
#     print(indx, len(x), len(y))

In [45]:
#Define Network
class MyNet(nn.Module):
    def __init__(self):
        super(MyNet, self).__init__()
        self.conv1 = nn.Conv2d(1, 6, 3)
        self.conv2 = nn.Conv2d(6, 16, 3)
        
        self.fc1 = nn.Linear(9216, 120)
        self.fc2 = nn.Linear(120, 84)
        self.fc3 = nn.Linear(84, 10)
    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
#         print(x.size())
        x = x.view(-1, 16 * 24 * 24)
        x = self.fc1(x)
        x = F.relu(x)
        x = self.fc2(x)
        x = F.relu(x)
        x = self.fc3(x)
#         x = F.softmax(x)
        return x
        
        
model = MyNet()
print(model)

MyNet(
  (conv1): Conv2d(1, 6, kernel_size=(3, 3), stride=(1, 1))
  (conv2): Conv2d(6, 16, kernel_size=(3, 3), stride=(1, 1))
  (fc1): Linear(in_features=9216, out_features=120, bias=True)
  (fc2): Linear(in_features=120, out_features=84, bias=True)
  (fc3): Linear(in_features=84, out_features=10, bias=True)
)


In [46]:
x = torch.rand((1, 1, 28,28))
print(x.shape)
print(model(x))

torch.Size([1, 1, 28, 28])
tensor([[ 0.1069, -0.0569, -0.0434,  0.0415,  0.0406, -0.0196,  0.0426,  0.0221,
          0.0152, -0.0718]], grad_fn=<AddmmBackward>)


In [47]:
optimizer = optim.Adam(model.parameters(), lr=0.0001)
criterion =nn.CrossEntropyLoss()

In [50]:
for epoch in range(0, 64):
    for i, (x, y) in enumerate(train_set_loader):
#         print(i)
        
        optimizer.zero_grad()
        #Forward pass
#         print(y)
        y_hat = model(x)
        #Loss computed
        loss = criterion(y_hat, y)
        #Backward pass
        loss.backward()
        #Optimize
        optimizer.step()
        if(i % 32 ==0):
            print("Loss:", loss.item())
    print("*" * 101)
        
        
        

Loss: 0.2304443120956421
Loss: 0.4014715850353241
Loss: 0.4418361485004425
Loss: 0.3108752965927124
Loss: 0.26754486560821533
Loss: 0.26072078943252563
Loss: 0.37420985102653503
Loss: 0.2554911971092224
Loss: 0.41013747453689575
Loss: 0.20458996295928955
Loss: 0.33240649104118347
Loss: 0.3227280378341675
Loss: 0.33724915981292725
Loss: 0.18334148824214935
Loss: 0.13206960260868073
*****************************************************************************************************
Loss: 0.17645931243896484
Loss: 0.3427405059337616
Loss: 0.3721795082092285
Loss: 0.24207377433776855
Loss: 0.20335835218429565
Loss: 0.1916133612394333
Loss: 0.2831363081932068
Loss: 0.20550407469272614
Loss: 0.3420243561267853
Loss: 0.17374704778194427
Loss: 0.2846646308898926
Loss: 0.2515373229980469
Loss: 0.2514984607696533
Loss: 0.11725575476884842
Loss: 0.0920596495270729
*****************************************************************************************************
Loss: 0.14509451389312744
Loss:

Loss: 0.0051813554018735886
Loss: 0.011984542943537235
*****************************************************************************************************
Loss: 0.024162622168660164
Loss: 0.028642909601330757
Loss: 0.08929117023944855
Loss: 0.014438423328101635
Loss: 0.006981978192925453
Loss: 0.02226550132036209
Loss: 0.0239567868411541
Loss: 0.023440107703208923
Loss: 0.061264198273420334
Loss: 0.019176840782165527
Loss: 0.05324073135852814
Loss: 0.02977192960679531
Loss: 0.0295840073376894
Loss: 0.004799955990165472
Loss: 0.010375084355473518
*****************************************************************************************************
Loss: 0.021776659414172173
Loss: 0.025590170174837112
Loss: 0.0824725478887558
Loss: 0.012789133936166763
Loss: 0.0061498344875872135
Loss: 0.017877208068966866
Loss: 0.02277684211730957
Loss: 0.020162655040621758
Loss: 0.05568278580904007
Loss: 0.01795399934053421
Loss: 0.048368409276008606
Loss: 0.02898664027452469
Loss: 0.0272555872797966


Loss: 0.0026808534748852253
Loss: 0.0047990623861551285
Loss: 0.009329200722277164
Loss: 0.0016209414461627603
Loss: 0.0008460156386718154
Loss: 0.0012657950865104795
Loss: 0.006602470763027668
Loss: 0.0042228857055306435
Loss: 0.01191147230565548
Loss: 0.00910866353660822
Loss: 0.0051984298042953014
Loss: 0.003724757581949234
Loss: 0.0049323635175824165
Loss: 0.0007295322138816118
Loss: 0.002769649727270007
*****************************************************************************************************
Loss: 0.002493649022653699
Loss: 0.00486077181994915
Loss: 0.008380357176065445
Loss: 0.001323555945418775
Loss: 0.0006179901538416743
Loss: 0.0013426184887066483
Loss: 0.00559595413506031
Loss: 0.0029230802319943905
Loss: 0.009828770533204079
Loss: 0.007844042964279652
Loss: 0.005463659297674894
Loss: 0.0028558613266795874
Loss: 0.0046917712315917015
Loss: 0.0006369343609549105
Loss: 0.002179135102778673
*****************************************************************************

Loss: 0.0004127173451706767
Loss: 0.0010393360862508416
Loss: 0.001616740133613348
Loss: 0.00011678467853926122
Loss: 9.407508332515135e-05
Loss: 0.00041306164348497987
Loss: 0.0011034136405214667
Loss: 0.0005265377694740891
Loss: 0.0038826323579996824
Loss: 0.001013203407637775
Loss: 0.007830750197172165
Loss: 0.00022231122420635074
Loss: 0.0009080214658752084
Loss: 0.0001092118545784615
Loss: 0.000143490222399123
*****************************************************************************************************
Loss: 0.0003661442897282541
Loss: 0.0006346864975057542
Loss: 0.0018047834746539593
Loss: 6.324654532363638e-05
Loss: 0.0001292101078433916
Loss: 0.00017558071704115719
Loss: 0.0005715928273275495
Loss: 0.0008954054792411625
Loss: 0.004063677508383989
Loss: 0.0008461916004307568
Loss: 0.0028852049726992846
Loss: 0.000783915922511369
Loss: 0.0005520062404684722
Loss: 0.0014351843856275082
Loss: 0.0001882297219708562
************************************************************

In [129]:
# params = list(model.parameters())
# print(len(params))
# print(params[0].size())
# print(params[0])

In [118]:


# for l in model.parameters():
    

tensor([[ 0.0222,  0.0831,  0.0796, -0.0663,  0.0609, -0.0461, -0.1055, -0.0828,
          0.0555, -0.0635]], grad_fn=<AddmmBackward>)
<generator object Module.parameters at 0x7fc18f60e5c8>


In [119]:
print(model(x))

tensor([[ 0.0222,  0.0831,  0.0796, -0.0663,  0.0609, -0.0461, -0.1055, -0.0828,
          0.0555, -0.0635]], grad_fn=<AddmmBackward>)
